export const SIGNUP_DETAILS = 'SIGNUP_DETAILS'
export const LOGGEDIN_USER = "LOGGEDIN_USER"
export const STORE_TOKEN = "STORE_TOKEN"
export const LOGOUT_USER = "LOGOUT_USER"
export const LOGIN_ERROR = "LOGIN_ERROR"